services:
  gw:
    #image: "${DOCKER_IMAGE}"
    image: sipmediagw2
    build:
      context: .
    restart: ${RESTART}
    container_name: gw${ID}
    network_mode: host
    tmpfs:
      - /tmp
    volumes:
      - ./logs:/var/logs
    devices:
      - /dev/video${ID}:/dev/video0
      - /dev/snd:/dev/snd
    shm_size: '2gb'
    logging:
      #driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    env_file:
      - .env
      - test/.env_kamailio
      - test/.env_turn
    environment:
      TZ: "${HOST_TZ}" # Time Zone
      GW_ID: "${ID}"
      SIP_NAME_PREFIX: "${PREFIX}"
      ROOM_NAME: "${ROOM}"
    stop_grace_period: 20s
